---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-deployment
  labels:
    name: httpd-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      name: httpd-pod
  template:
    metadata:
      name: httpd-pod
      labels:
        name: httpd-pod
    spec:
      containers:
        - name: myhttpd
          image: httpd
          ports:
            - containerPort: 80
      tolerations:
        - key: "slave2"
          operator: "Equal"
          value: "machine2"
          effect: "NoSchedule"
---





...